version: '3.8'

# Infrastructure

services:
  rabbitmq:
    container_name: worksphere_rabbitmq
    image: rabbitmq:4.0.8-management
    hostname: rabbitmq
    env_file: .env
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-password}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST:-/work_sphere_default}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'status']
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  rabbitmq_data:
